### ISSUE TITLE
Framework currently does not support 16K 

### ISSUE THREAD

**Issue by reyee22** [ViroCommunity/viro#400]
Currently, the framework does not support 16 KB memory page size.
Starting November 1, 2025, Google Play requires all new and updated Android apps targeting Android 15 (API 35) or higher to be compatible with 16 KB page size devices.

If the framework (especially native .so libraries) is not built or aligned for 16 KB pages, apps using this SDK may fail to run on future Android devices or be rejected by Google Play during submission.

To ensure compliance and forward compatibility, ViroReact should add full support for 16 KB memory page size across all components, particularly on Android.

**Comment by allthetime** [comment]
They will absolutely be rejected. There is a grade period reaching into early 2026, but beyond that you will no longer be able to upload an app running these current versions to Google Play

**Comment by chartungpatmos** [comment]
I don't know why no one responded here, but according to the release notes, this is resolved: https://github.com/ReactVision/viro/releases/tag/v2.44.1

**Comment by oliedis** [comment]
Hey this is resolved from 2.44.1 onwards

**Comment by ngioldasis** [comment]
Hi,
I'm using 2.56.0 and I still get the 16KB incompatibility error. It seems that  despite in the 2.44.2 changelog (https://github.com/ReactVision/viro/releases/tag/v2.44.1) claim, the shipped viro_renderer-release.aar in v2.56.0 still has non-aligned .so files. 

Actual offenders (arm64-v8a — your target ABI):
viro_renderer-release.aar → jni/arm64-v8a/libc++_shared.so (4KB aligned)
viro_renderer-release.aar → jni/arm64-v8a/libopenxr_loader.so (4KB aligned)

Does anyone else have this issue? Am I doing something wrong?
